'use strict';
(() => {
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),W=1280,H=720,FLOOR=586;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rand=(a,b)=>a+Math.random()*(b-a),keys=new Set();
let atlas,data,tinted={},state='loading',player,enemies=[],particles=[],texts=[],time=0,wave=0,waveWait=0,freeze=0,shake=0,flash=0,combo=0,comboTime=0,kills=0,elapsed=0,audio=null,sound=true,reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,nextID=1;
let counters={jumps:0,landings:0,hits:0,kills:0,damage:0,slams:0,dodges:0,heavyHits:0};
const overlay=document.querySelector('#overlay'),result=document.querySelector('#result'),start=document.querySelector('#start');
function tone(freq=70,duration=.15,type='triangle',vol=.15,slide=.3){if(!sound||!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(15,freq*slide),audio.currentTime+duration);g.gain.setValueAtTime(vol,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+duration)}
function noise(duration=.12,volume=.12){if(!sound||!audio)return;const n=Math.ceil(audio.sampleRate*duration),b=audio.createBuffer(1,n,audio.sampleRate),v=b.getChannelData(0);for(let i=0;i<n;i++)v[i]=(Math.random()*2-1)*Math.pow(1-i/n,2);const s=audio.createBufferSource(),g=audio.createGain();s.buffer=b;g.gain.value=volume;s.connect(g).connect(audio.destination);s.start()}
function unlock(){if(!audio){try{audio=new(window.AudioContext||window.webkitAudioContext)()}catch{}}audio?.resume()}
function impact(x,y,power=1,color='#ffc471'){shake=Math.max(shake,power*7);flash=Math.max(flash,power*.1);freeze=Math.max(freeze,.045+power*.025);for(let i=0;i<12+power*8;i++)particles.push({x,y,vx:rand(-280,280)*power,vy:rand(-300,100)*power,life:rand(.12,.45),max:.45,color,size:rand(2,5),gravity:700});tone(75,.17,'triangle',.14*power,.2);noise(.1,.09*power)}
function dust(x,power=1){for(let i=0;i<15;i++)particles.push({x:x+rand(-20,20),y:FLOOR-3,vx:rand(-140,140)*power,vy:rand(-90,-10),life:rand(.2,.55),max:.55,color:'#8c7c69',size:rand(3,9),gravity:50})}
function label(x,y,text,color='#ffc471'){texts.push({x,y,text,color,life:.85})}
function fighter(x,enemy=false,tough=false){return{id:nextID++,x,y:FLOOR,vx:0,vy:0,face:enemy?-1:1,hp:enemy?(tough?100:70):100,max:enemy?(tough?100:70):100,enemy,tough,ground:true,action:'idle',t:0,hit:false,cool:0,slamCool:0,dodge:0,inv:0,stun:0,ai:rand(.5,1),dead:0,slam:false,land:0,anim:0}}
function begin(){unlock();keys.clear();player=fighter(380);enemies=[];particles=[];texts=[];wave=0;waveWait=.65;combo=0;comboTime=0;kills=0;elapsed=0;freeze=0;shake=0;flash=0;counters={jumps:0,landings:0,hits:0,kills:0,damage:0,slams:0,dodges:0,heavyHits:0};state='playing';overlay.hidden=true;result.hidden=true;tone(90,.5,'sawtooth',.08,.5)}
function spawnWave(){wave++;const count=[2,3,4][wave-1];enemies=Array.from({length:count},(_,i)=>fighter(i%2?1080-i*35:170+i*45,true,wave===3&&i===count-1));enemies.forEach((e,i)=>e.ai=.6+i*.5);label(640,220,`ROUND ${String(wave).padStart(2,'0')} / 03`);tone(130,.3,'sawtooth',.06,.6)}
function end(won){state=won?'victory':'dead';keys.clear();result.hidden=false;document.querySelector('#result-label').textContent=won?'THE FOUNDRY FALLS SILENT':'THE FOUNDRY KEEPS WHAT IT IS OWED';document.querySelector('#result-title').textContent=won?'VERDICT: SURVIVED':'IRON BREAKS, TOO.';document.querySelector('#result-copy').textContent=won?`${kills} opponents down in ${Math.round(elapsed)} seconds. ${Math.ceil(player.hp)} armor left. You earned the quiet.`:`Round ${wave} · ${kills} opponents down. Dodge through amber windups, interrupt with heavy strikes, and slam into groups from above.`;tone(won?220:60,.6,'triangle',.12,won?1.5:.4)}
function attack(kind){if(state!=='playing'||player.stun>0||player.action==='dodge'||['attack','heavy','slam','land'].includes(player.action)||player.cool>0)return;if(kind==='heavy'&&!player.ground){if(player.slamCool>0)return;player.slamCool=1.3;player.action='slam';player.slam=true;player.vy=1150;player.vx*=.3;player.t=0;counters.slams++;tone(180,.16,'sawtooth',.045,.4);return}if(player.cool>0)return;player.action=kind;player.t=0;player.hit=false;player.cool=kind==='heavy'?.72:.34;tone(kind==='heavy'?120:200,.08,'triangle',.045,.4)}
function input(key){if(state!=='playing')return;if(key===' '&&player.ground&&player.stun<=0&&!['dodge','attack','heavy','slam','land'].includes(player.action)){player.vy=-890;player.ground=false;player.action='jump';player.t=0;counters.jumps++;dust(player.x,.5);tone(120,.14,'triangle',.05,1.5)}else if(key==='j')attack('attack');else if(key==='k')attack('heavy');else if(key==='Shift'&&player.dodge<=0&&player.stun<=0&&player.action!=='slam'){player.action='dodge';player.t=0;player.inv=.24;player.dodge=1.15;player.vx=player.face*780;counters.dodges++;noise(.12,.05);dust(player.x,.7)}}
const controlled=new Set(['a','d','ArrowLeft','ArrowRight',' ','j','k','Shift','r']);
addEventListener('keydown',e=>{let k=e.key.length===1?e.key.toLowerCase():e.key;if(!controlled.has(k))return;if(k===' '&&e.target instanceof HTMLButtonElement)return;e.preventDefault();if(k==='r'&&state!=='loading'&&state!=='error'){begin();return}if(!keys.has(k))input(k);keys.add(k)});addEventListener('keyup',e=>keys.delete(e.key.length===1?e.key.toLowerCase():e.key));addEventListener('blur',()=>keys.clear());
document.querySelectorAll('[data-key]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);const k=b.dataset.key;keys.add(k);input(k)});for(const type of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(type,()=>keys.delete(b.dataset.key))});
start.addEventListener('click',begin);document.querySelector('#restart').addEventListener('click',begin);document.querySelector('#sound').addEventListener('click',e=>{sound=!sound;e.currentTarget.textContent=`Sound: ${sound?'on':'off'}`;e.currentTarget.setAttribute('aria-pressed',sound);if(sound)unlock()});function motionButton(){let b=document.querySelector('#motion');b.textContent=`Motion: ${reduced?'reduced':'full'}`;b.setAttribute('aria-pressed',reduced)}motionButton();document.querySelector('#motion').addEventListener('click',()=>{reduced=!reduced;motionButton()});
function hurt(target,damage,dir,power=1){if(target.hp<=0||target.inv>0)return false;target.hp=Math.max(0,target.hp-damage);target.stun=target.enemy?.24+power*.08:.3;target.inv=target.enemy?.09:.6;target.action='hurt';target.slam=false;target.t=0;target.vx=dir*(target.enemy?240:190)*power;target.vy=target.ground?-90:target.vy-80;target.ground=false;impact(target.x,target.y-100,power,target.enemy?'#ffbd71':'#ff6651');label(target.x,target.y-185,String(damage),target.enemy?'#ffe4b2':'#ff8070');if(target.enemy){counters.hits++;combo++;comboTime=2;if(target.hp<=0){kills++;counters.kills++;target.dead=.7;target.vx=dir*350;label(target.x,target.y-225,'BROKEN')}}else{counters.damage+=damage;combo=0}return true}
function strike(p,heavy=false){let connected=false;for(const e of enemies){if(e.hp<=0)continue;const dx=e.x-p.x;if(dx*p.face>-25&&dx*p.face<(heavy?155:128)&&Math.abs((e.y-100)-(p.y-100))<105){connected=hurt(e,heavy?38:22,p.face,heavy?1.35:.75)||connected;if(heavy)counters.heavyHits++}}if(!connected)noise(.06,.045);p.vx+=p.face*(heavy?130:70)}
function updateFighter(f,dt){f.anim+=dt;f.land=Math.max(0,f.land-dt);f.slamCool=Math.max(0,f.slamCool-dt);f.cool=Math.max(0,f.cool-dt);f.inv=Math.max(0,f.inv-dt);f.dodge=Math.max(0,f.dodge-dt);f.stun=Math.max(0,f.stun-dt);f.t+=dt;const previousGround=f.ground;if(f.hp<=0){f.dead=Math.max(0,f.dead-dt);f.vx*=Math.exp(-dt*3)}else if(f.stun>0){f.vx*=Math.exp(-dt*6)}else if(f.enemy){const dx=player.x-f.x;if(!['windup','attack'].includes(f.action))f.face=dx>=0?1:-1;if(f.action==='windup'){f.vx=0;if(f.t>.7){f.action='attack';f.t=0;f.hit=false;tone(150,.1,'sawtooth',.035,.3)}}else if(f.action==='attack'){f.vx=f.face*80;if(f.t>.1&&!f.hit){f.hit=true;if((player.x-f.x)*f.face>-30&&(player.x-f.x)*f.face<145&&Math.abs(player.y-f.y)<115)hurt(player,f.tough?26:19,f.face,1)}if(f.t>.48){f.action='idle';f.ai=rand(.65,1.15);f.t=0}}else{f.ai-=dt;const attackBusy=enemies.some(e=>e!==f&&['windup','attack'].includes(e.action));if(Math.abs(dx)<115&&f.ai<=0&&!attackBusy&&player.hp>0){f.action='windup';f.t=0;f.vx=0;tone(460,.06,'sine',.025,.9)}else{f.vx=Math.abs(dx)>100?f.face*(f.tough?115:145):0;f.action=f.vx?'walk':'idle';for(const other of enemies){if(other===f||other.hp<=0)continue;let gap=f.x-other.x;if(Math.abs(gap)<65)f.vx+=Math.sign(gap||1)*65}}}}else{
 if(f.action==='land'){f.vx*=Math.exp(-dt*15);if(f.t>.13)f.action='idle'}else if(f.action==='dodge'){f.vx=f.face*720;if(f.t>.22){f.action=f.ground?'idle':'jump';f.vx*=.35}}else if(f.action==='attack'||f.action==='heavy'){const heavy=f.action==='heavy';f.vx*=Math.exp(-dt*10);if(f.t>(heavy?.26:.14)&&!f.hit){f.hit=true;strike(f,heavy)}if(f.t>(heavy?.52:.28)){f.action=f.ground?'idle':'jump';f.t=0}}else if(f.action==='slam'){f.vx*=Math.exp(-dt*4)}else{const dir=(keys.has('d')||keys.has('ArrowRight')?1:0)-(keys.has('a')||keys.has('ArrowLeft')?1:0);if(dir)f.face=dir;const target=dir*(f.ground?300:265);f.vx+=(target-f.vx)*Math.min(1,dt*(f.ground?18:8));f.action=f.ground?(dir?'walk':'idle'):'jump'}
 }
 f.x=clamp(f.x+f.vx*dt,70,1210);if(!f.ground){f.vy+=3200*dt;f.y+=f.vy*dt;if(f.y>=FLOOR){const speed=f.vy;f.y=FLOOR;f.vy=0;f.ground=true;f.land=.13;if(!f.enemy&&f.hp>0){counters.landings++;dust(f.x,Math.min(2,speed/500));shake=Math.max(shake,speed>800?8:3);tone(48,.16,'triangle',.12,.35);if(f.slam){f.slam=false;impact(f.x,FLOOR-15,1.8);for(const e of enemies)if(Math.abs(e.x-f.x)<185&&e.hp>0){hurt(e,36,Math.sign(e.x-f.x)||f.face,1.5);counters.heavyHits++}label(f.x,FLOOR-210,'GROUND BREAK');f.action='land';f.t=0;f.hit=true;f.cool=.55}else if(f.action==='jump'){f.action='land';f.t=0}}}}else if(!previousGround)f.y=FLOOR;
}
function update(dt){time+=dt;shake=Math.max(0,shake-dt*35);flash=Math.max(0,flash-dt*2);for(const p of particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=p.gravity*dt;p.life-=dt}particles=particles.filter(p=>p.life>0);for(const t of texts){t.y-=35*dt;t.life-=dt}texts=texts.filter(t=>t.life>0);if(state!=='playing')return;if(freeze>0){freeze-=dt;return}elapsed+=dt;comboTime-=dt;if(comboTime<=0)combo=0;updateFighter(player,dt);for(const e of enemies)updateFighter(e,dt);if(player.hp<=0){end(false);return}if(!enemies.some(e=>e.hp>0)){waveWait-=dt;if(waveWait<=0){if(wave===3){end(true);return}if(wave>0){player.hp=Math.min(100,player.hp+18);label(player.x,player.y-200,'+18 ARMOR','#a8e0bd')}spawnWave();waveWait=1.8}}}
function rect(x,y,w,h,color){ctx.fillStyle=color;ctx.fillRect(x,y,w,h)}
function txt(text,x,y,size=12,color='#c9c1b1',align='left',weight=700){ctx.fillStyle=color;ctx.font=`${weight} ${size}px Arial`;ctx.textAlign=align;ctx.fillText(text,x,y)}
function background(){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#121a20');g.addColorStop(.7,'#252124');g.addColorStop(1,'#0d1014');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);for(let i=0;i<8;i++){let x=i*190-35;rect(x,0,30,FLOOR,'#10171c');rect(x+30,0,5,FLOOR,'#333335');rect(x+38,130,128,4,'#343438');rect(x+38,350,128,4,'#343438')}for(const x of [210,920]){rect(x,160,155,355,'#0d1015');const glow=ctx.createLinearGradient(0,210,0,510);glow.addColorStop(0,'#481f19');glow.addColorStop(.65,'#bb5026');glow.addColorStop(1,'#ffd07c');ctx.fillStyle=glow;ctx.fillRect(x+9,180,137,327);for(let i=0;i<7;i++)rect(x+9+i*21,180,8,327,'#211b1a');rect(x-12,154,179,15,'#4b4440');rect(x-12,505,179,17,'#4b4440')}const glow=ctx.createRadialGradient(640,520,50,640,490,500);glow.addColorStop(0,'#e267241d');glow.addColorStop(1,'#e2672400');ctx.fillStyle=glow;ctx.fillRect(0,0,W,H);for(let x=60;x<W;x+=280){rect(x,0,6,125,'#030a0e');rect(x-22,117,50,12,'#574c3b');rect(x-16,129,38,4,'#f3bf79')}txt('FOUNDRY / 09',640,310,74,'#69605720','center',900);txt('NO APPEALS',640,344,13,'#a7927140','center');rect(0,FLOOR,W,H-FLOOR,'#191c1f');rect(0,FLOOR, W,8,'#807564');rect(0,FLOOR+8,W,5,'#090e12');for(let i=0;i<18;i++){ctx.strokeStyle='#373635';ctx.beginPath();ctx.moveTo(i*90-160,FLOOR+16);ctx.lineTo(i*105-260,H);ctx.stroke()}for(let y=FLOOR+28;y<H;y+=37)rect(0,y,W,2,'#2c2d2c');for(let x=0;x<W;x+=52){ctx.fillStyle='#b37c3760';ctx.beginPath();ctx.moveTo(x,FLOOR+14);ctx.lineTo(x+22,FLOOR+14);ctx.lineTo(x+5,FLOOR+29);ctx.lineTo(x-17,FLOOR+29);ctx.fill()}for(let i=0;i<25;i++){let x=(i*137+Math.sin(time*.5+i)*20)%W,y=540-((time*18+i*41)%450);rect(x,y,2,3,`rgba(255,165,74,${.15+Math.sin(i+time)*.1})`)}}
function drawFighter(f){if(f.hp<=0&&f.dead<=0)return;let anim=f.action==='walk'?'walk':['attack','heavy','windup'].includes(f.action)?'attack':(!f.ground||f.action==='jump'||f.land>0)?'jump':'idle';if(!data.animations[anim])anim='idle';const frames=data.animations[anim].frames;let idx;if(f.action==='windup')idx=1;else if(f.action==='attack'||f.action==='heavy')idx=Math.min(frames.length-1,Math.floor(f.t/(f.action==='heavy'?.52:.28)*frames.length));else if(anim==='jump')idx=f.land>0?(f.land>.065?6:7):f.action==='slam'?5:f.vy< -700?1:f.vy< -200?2:f.vy<200?3:f.vy<500?4:5;else idx=Math.floor(f.anim*(anim==='walk'?12:7))%frames.length;const entry=data.frames[frames[clamp(idx,0,frames.length-1)]];if(!entry)return;const r=entry.frame,s=f.enemy?(f.tough?1.18:1.05):1.15;ctx.save();ctx.globalAlpha=f.hp<=0?f.dead/.7:1;ctx.fillStyle='#0007';ctx.beginPath();ctx.ellipse(f.x,FLOOR+2,56*s*Math.max(.4,1-(FLOOR-f.y)/400),12,0,0,Math.PI*2);ctx.fill();ctx.translate(f.x,f.y);if(f.action==='dodge'){ctx.globalAlpha=.6;ctx.translate(0,15);ctx.scale(1,.86)}ctx.scale(f.face*s,s);if(f.hp<=0)ctx.rotate(-f.face*.8*(1-f.dead/.7));const sprite=f.inv>0&&Math.floor(time*35)%2===0?tinted.flash:f.enemy?(f.tough?tinted.tough:tinted.enemy):atlas;ctx.drawImage(sprite,r.x,r.y,r.w,r.h,-128,-236,256,256);ctx.restore();if(f.enemy&&f.hp>0){const y=f.y-227*s;rect(f.x-36,y,72,5,'#0a0e12');rect(f.x-36,y,72*f.hp/f.max,5,f.tough?'#db6a50':'#c69a62');if(f.action==='windup'){const p=clamp(f.t/.7,0,1);ctx.strokeStyle=p>.7?'#ff6147':'#ffc369';ctx.lineWidth=3;ctx.beginPath();ctx.arc(f.x,f.y-115,65,0,Math.PI*2*p);ctx.stroke();txt('!',f.x,y-13,28,p>.7?'#ff6147':'#ffc369','center');ctx.fillStyle=`rgba(255,80,40,${.1+p*.13})`;ctx.beginPath();ctx.ellipse(f.x+f.face*60,FLOOR+2,110,15,0,0,Math.PI*2);ctx.fill()}}}
function hud(){const grad=ctx.createLinearGradient(0,0,0,150);grad.addColorStop(0,'#060b11ee');grad.addColorStop(1,'#060b1100');ctx.fillStyle=grad;ctx.fillRect(0,0,W,150);txt('FURNACE KNIGHT',40,40,13,'#ece1ce');txt('ARMOR',40,62,10,'#a09483');rect(95,53,255,12,'#3b2927');rect(95,53,255*player.hp/100,12,player.hp<30?'#ee6551':'#eca66a');txt(String(Math.ceil(player.hp)).padStart(3,'0'),365,65,17,'#efd8bc');txt('DODGE',40,87,9,'#a09483');rect(95,80,110,4,'#373b3e');rect(95,80,110*(1-player.dodge/1.15),4,'#a7cdd0');txt(player.dodge>0?'COOLING':'READY',218,87,9,player.dodge>0?'#8c8982':'#a7cdd0');txt('SLAM',40,106,9,'#a09483');rect(95,99,110,4,'#373b3e');rect(95,99,110*(1-player.slamCool/1.3),4,'#e3ad73');txt(player.slamCool>0?'COOLING':'READY',218,106,9,player.slamCool>0?'#8c8982':'#e3ad73');txt('IRON VERDICT',640,40,22,'#f0d6b0','center',900);txt(`ROUND ${String(wave).padStart(2,'0')} / 03`,640,63,11,'#b5a792','center');txt(`${kills} / 9 BROKEN`,1240,43,16,'#ebbf87','right');txt(`${Math.floor(elapsed/60)}:${String(Math.floor(elapsed%60)).padStart(2,'0')}`,1240,65,11,'#9d9588','right');if(combo>1){txt(`${combo} HITS`,1235,127,32,'#ffb768','right',900);txt('KEEP THE PRESSURE',1235,147,9,'#c1a990','right')}if(player.hp<30){txt('ARMOR CRITICAL',640,105,12,'#ff7056','center')}txt('J  PUNCH    K  HEAVY / AIR SLAM    SPACE  JUMP    SHIFT  DODGE',640,693,10,'#8e8980','center')}
function draw(){ctx.save();if(!reduced&&shake>0)ctx.translate(rand(-shake,shake),rand(-shake,shake)*.6);background();if(player){for(const f of [...enemies,player].sort((a,b)=>a.y-b.y))drawFighter(f)}else if(data){drawFighter({...fighter(640),anim:time})}for(const p of particles){ctx.globalAlpha=clamp(p.life/p.max,0,1);rect(p.x,p.y,p.size,p.size,p.color)}ctx.globalAlpha=1;for(const t of texts)txt(t.text,t.x,t.y, t.text.length>5?22:26,t.color,'center',900);ctx.restore();if(!reduced&&flash>0)rect(0,0,W,H,`rgba(255,202,139,${Math.min(.18,flash)})`);const vignette=ctx.createRadialGradient(640,350,250,640,350,750);vignette.addColorStop(0,'#0000');vignette.addColorStop(1,'#0008');ctx.fillStyle=vignette;ctx.fillRect(0,0,W,H);if(player)hud()}
let last=performance.now();function frame(now){const dt=Math.min(.033,(now-last)/1000);last=now;update(dt);draw();requestAnimationFrame(frame)}
Object.defineProperty(window,'__arena',{value:Object.freeze({snapshot:()=>({state,wave,elapsed,player:player?{x:player.x,y:player.y,vx:player.vx,vy:player.vy,hp:player.hp,ground:player.ground,action:player.action,actionTime:player.t,cooldown:player.cool,slamCooldown:player.slamCool,invulnerability:player.inv,dodge:player.dodge}:null,enemies:enemies.map(e=>({id:e.id,x:e.x,y:e.y,hp:e.hp,action:e.action,actionTime:e.t,facing:e.face})),events:{...counters},reducedMotion:reduced,sound,combo})}),writable:false});
Promise.all([fetch('assets/atlas.json').then(r=>{if(!r.ok)throw Error('atlas metadata unavailable');return r.json()}),new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=()=>reject(Error('atlas image unavailable'));i.src='assets/atlas.png'})]).then(([json,img])=>{data=json;atlas=img;for(const [name,filter] of Object.entries({enemy:'sepia(.7) saturate(.8) hue-rotate(125deg) brightness(.85)',tough:'sepia(.7) saturate(2.3) hue-rotate(315deg) brightness(.85)',flash:'brightness(1.8)'})){const c=document.createElement('canvas');c.width=img.width;c.height=img.height;const cx=c.getContext('2d');cx.filter=filter;cx.drawImage(img,0,0);tinted[name]=c}state='ready';start.disabled=false;start.textContent='ENTER THE FURNACE';requestAnimationFrame(frame)}).catch(error=>{state='error';start.textContent='ASSETS COULD NOT LOAD';document.querySelector('#intro').textContent='Serve this folder over HTTP with its assets directory intact.';console.error(error)});
})();
